import tkinter as tk
w = tk.Tk()
w.minsize(350, 200)
w.title("Example Form")
tk.Label(w, text="Example", font=("Arial", 14)).grid(row=0, column=2)
tk.Label(w, text="First Name").grid(row=1, column=1)
tk.Entry(w, bd=5).grid(row=1, column=2)
tk.Label(w, text="Last Name").grid(row=2, column=1)
tk.Entry(w, bd=5).grid(row=2, column=2)
tk.Label(w, text="Email Id").grid(row=3, column=1)
tk.Entry(w, bd=5).grid(row=3, column=2)
tk.Label(w, text="Contact Number").grid(row=4, column=1)
tk.Entry(w, bd=5).grid(row=4, column=2)
tk.Button(w, text="Submit", bd=5, bg="lightgray").grid(row=5, column=2, pady=10)
w.mainloop()