x,y=2,3

print(" x = ", " y = ", y)
print(" \nx + y = ", x + y)
print(" x.__add__(y) = ", x.__add__(y))
print(" \nx - y = ", x - y)
print(" x.__sub__(y) = ", x.__sub__(y))
print(" \nx * y = ", x * y)
print(" x.__mul__(y) = ", x.__mul__(y))
print(" \nx / y = ", x / y)
print(" x.__truediv__(y) = ",x.__truediv__(y))
print(" \nx ** y = ", x ** y)
print(" x.__pow__(y) = ",x.__pow__(y))
print(" \nx % y = ", x % y)
print(" x.__mod__(y) = ",x.__mod__(y))
print(" \nx == y = ", x == y)
print(" x.__eq__(y) = ",x.__eq__(y))
print(" \nx != y = ", x != y)
print(" x.__ne__(y) = ",x.__ne__(y))
print(" \nx >= y = ", x >= y)
print(" x.__ge__(y) = ",x.__ge__(y))
print(" \nx <= y = ",x <= y)
print(" x.__le__(y) = ",x.__le__(y))
print("------------------")
strl = " special method "
print(" \nstel = ", strl)
