import tkinter as tk
w=tk.Tk()
w.title("Frame")
frame1=tk.Frame(w, cursor="cross")
lbl1=tk.Label(frame1,text="FYCS", bg="yellow")
lbl1.pack()
msg=tk.Message(frame1,text="This is CS class",bg="light green", font=("Arial"))
msg.pack()
txt=tk.Text(frame1,font=("Courier",15), width="50" ,height="20")
txt.pack()
btn1=tk.Button(frame1, text="Submit", relief="sunken")
btn1.pack()
frame1.pack()
w.mainloop()
